### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by caspahouzer** [FokkeZB/IconFont#8]
iconfont ./vendor/fontawesome/css/all.css ./app/lib/fontawesome.js

produces

```
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/usr/local/lib/node_modules/iconfont/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/iconfont/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/iconfont/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)```

I'm using node v12.21.0

**Comment by FokkeZB** [comment]
Fixed by #9, published as 0.4.1
